# Setup
title:                      냐웅냐웅
tagline:                    '어쩌란 말인가...'
description:                '냐웅냐웅의 블로그'
url:                        https://nyaooooong.github.io
baseurl:                    '' 
paginate:                   3
permalink:                  pretty
sass:
    sass_dir:               _sass

category_dir:               category
tag_dir:                    tag

# About/contact
author:
  name:                     Not Real Name
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:                    1.0.0
google_analytics_id: 
