# Setup
title:               냐웅냐웅
tagline:             '어쩌란 말인가...'
description:         '냐웅냐웅의 블로그'
url:                 https://nyaooooong.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Not Real Name
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: 
